######################################################################
##
## Filename: ram4_ram4_sch_tb.udo
## Created on: Tue May 28 11:12:34 CEST 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
