######################################################################
##
## Filename: reg4.udo
## Created on: Tue May 28 13:46:37 CEST 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
