######################################################################
##
## Filename: mux4_mux4_sch_tb.udo
## Created on: Fri Apr 26 11:18:03 CEST 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
