######################################################################
##
## Filename: mux4.udo
## Created on: Fri Apr 26 11:13:11 CEST 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
