######################################################################
##
## Filename: alu1_alu1_sch_tb.udo
## Created on: Fri May 10 11:25:14 CEST 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
