######################################################################
##
## Filename: alu4flag_alu4flag_sch_tb.udo
## Created on: Fri May 10 15:01:08 CEST 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
