######################################################################
##
## Filename: flagdec4.udo
## Created on: Fri May 10 15:00:32 CEST 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
